# Generated by Django 6.0 on 2025-12-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_increase_extent_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='position',
            field=models.CharField(blank=True, help_text='Office or role (Gobernador, Alcalde, etc.)', max_length=200),
        ),
        migrations.AddField(
            model_name='entity',
            name='title',
            field=models.CharField(blank=True, help_text='Honorific (Don, Fray, Dr., etc.)', max_length=100),
        ),
    ]
