# Generated by Django 6.0 on 2025-12-11 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_entity_title_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='position',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='title',
        ),
        migrations.AddField(
            model_name='descriptionentity',
            name='function',
            field=models.CharField(blank=True, help_text='Function/office as recorded (Gobernador de Popayán)', max_length=300),
        ),
        migrations.AddField(
            model_name='descriptionentity',
            name='honorific',
            field=models.CharField(blank=True, help_text='Honorific as recorded in this document (Don, Fray)', max_length=100),
        ),
        migrations.AddField(
            model_name='descriptionentity',
            name='name_as_recorded',
            field=models.CharField(blank=True, help_text='Full name string as appears in document', max_length=500),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier (ne-xxxxx) for URLs and citations', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='honorific',
            field=models.CharField(blank=True, help_text='Primary form of address (Don, Fray, Dr.)', max_length=100),
        ),
        migrations.AddField(
            model_name='entity',
            name='primary_function',
            field=models.CharField(blank=True, help_text='Most notable office/role (Gobernador de Popayán)', max_length=300),
        ),
        migrations.CreateModel(
            name='EntityFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honorific', models.CharField(blank=True, help_text='Associated honorific if known', max_length=100)),
                ('function', models.CharField(help_text='The office, rank, or role held', max_length=300)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_note', models.CharField(blank=True, help_text='For uncertain dates: "ca. 1815", "before 1820"', max_length=100)),
                ('certainty', models.CharField(choices=[('certain', 'Cierto'), ('probable', 'Probable'), ('possible', 'Posible')], default='probable', max_length=20)),
                ('source', models.TextField(blank=True, help_text='How we know this: documents, external authority, etc.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_functions', to='catalog.entity')),
            ],
            options={
                'verbose_name': 'Known Function',
                'verbose_name_plural': 'Known Functions',
                'ordering': ['date_start', 'function'],
            },
        ),
    ]
