# Generated by Django 6.0 on 2026-02-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_entity_surname_given_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='ocr_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
