# Generated by Django 6.0 on 2026-02-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_repository_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='finding_aids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='description',
            name='section_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='repository',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
