# Generated by Django 6.0 on 2026-02-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_country_finding_aids_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='location_of_copies',
            field=models.TextField(blank=True),
        ),
    ]
