# Generated by Django 6.0 on 2026-02-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_add_location_of_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='viaf_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='wikidata_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hgis_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='place_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier (nl-xxxxx) for URLs and citations', max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tgn_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='whg_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionentity',
            name='role',
            field=models.CharField(choices=[('creator', 'Creador'), ('author', 'Autor'), ('editor', 'Editor'), ('publisher', 'Impresor/Editorial'), ('sender', 'Remitente'), ('recipient', 'Destinatario'), ('mentioned', 'Mencionado'), ('subject', 'Tema'), ('scribe', 'Escribano'), ('witness', 'Testigo'), ('notary', 'Notario'), ('photographer', 'Fotografo'), ('artist', 'Artista'), ('plaintiff', 'Demandante'), ('defendant', 'Demandado'), ('petitioner', 'Peticionario'), ('judge', 'Juez'), ('appellant', 'Apelante'), ('official', 'Oficial'), ('heir', 'Heredero'), ('albacea', 'Albacea'), ('spouse', 'Conyuge'), ('victim', 'Victima'), ('grantor', 'Otorgante'), ('donor', 'Donante'), ('seller', 'Vendedor'), ('buyer', 'Comprador'), ('mortgagor', 'Deudor hipotecario'), ('mortgagee', 'Acreedor hipotecario'), ('creditor', 'Acreedor'), ('debtor', 'Deudor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='descriptionplace',
            name='role',
            field=models.CharField(choices=[('created', 'Lugar de creacion'), ('subject', 'Tema/Asunto'), ('mentioned', 'Mencionado'), ('sent_from', 'Enviado desde'), ('sent_to', 'Enviado a'), ('published', 'Publicado en'), ('venue', 'Lugar del acto')], max_length=20),
        ),
    ]
