# Generated by Django 6.0 on 2026-04-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_m2_roles_and_lod_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description_level',
            field=models.CharField(choices=[('fonds', 'Fonds'), ('subfonds', 'Subfonds'), ('series', 'Series'), ('subseries', 'Subseries'), ('file', 'File'), ('item', 'Item'), ('collection', 'Collection'), ('section', 'Section'), ('volume', 'Volume')], max_length=20),
        ),
        migrations.AlterField(
            model_name='descriptionentity',
            name='function',
            field=models.CharField(blank=True, help_text='Function/office as recorded (Governor of Popayán)', max_length=300),
        ),
        migrations.AlterField(
            model_name='descriptionentity',
            name='honorific',
            field=models.CharField(blank=True, help_text='Honorific as recorded in this document (Don, Dr., Fray)', max_length=100),
        ),
        migrations.AlterField(
            model_name='descriptionentity',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('author', 'Author'), ('editor', 'Editor'), ('publisher', 'Publisher'), ('sender', 'Sender'), ('recipient', 'Recipient'), ('mentioned', 'Mentioned'), ('subject', 'Subject'), ('scribe', 'Scribe'), ('witness', 'Witness'), ('notary', 'Notary'), ('photographer', 'Photographer'), ('artist', 'Artist'), ('plaintiff', 'Plaintiff'), ('defendant', 'Defendant'), ('petitioner', 'Petitioner'), ('judge', 'Judge'), ('appellant', 'Appellant'), ('official', 'Official'), ('heir', 'Heir'), ('albacea', 'Executor'), ('spouse', 'Spouse'), ('victim', 'Victim'), ('grantor', 'Grantor'), ('donor', 'Donor'), ('seller', 'Seller'), ('buyer', 'Buyer'), ('mortgagor', 'Mortgagor'), ('mortgagee', 'Mortgagee'), ('creditor', 'Creditor'), ('debtor', 'Debtor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='descriptionplace',
            name='role',
            field=models.CharField(choices=[('created', 'Created'), ('subject', 'Subject'), ('mentioned', 'Mentioned'), ('sent_from', 'Sent from'), ('sent_to', 'Sent to'), ('published', 'Published'), ('venue', 'Venue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('person', 'Person'), ('family', 'Family'), ('corporate', 'Corporate entity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='primary_function',
            field=models.CharField(blank=True, help_text='Most notable office/role (Governor of Popayán)', max_length=300),
        ),
        migrations.AlterField(
            model_name='entityfunction',
            name='certainty',
            field=models.CharField(choices=[('certain', 'Certain'), ('probable', 'Probable'), ('possible', 'Possible')], default='probable', max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(blank=True, choices=[('country', 'Country'), ('region', 'Region'), ('department', 'Department'), ('province', 'Province'), ('partido', 'Partido (colonial)'), ('city', 'City'), ('town', 'Town'), ('parish', 'Parish'), ('hacienda', 'Hacienda'), ('mine', 'Mine'), ('river', 'River'), ('other', 'Other')], max_length=50),
        ),
    ]
